### ISSUE TITLE
Faculty jobs

### ISSUE THREAD

**Issue by ShGoldfish** [CSGraduateCouncil-VirginiaTech/csgc-website#143]
On the resources page for the [Faculty jobs](https://csgrad.cs.vt.edu/resources/#Jobs):
We need to add a link to the [whole folder ](https://drive.google.com/drive/folders/1xH1XBAkEfTZA8MXvu94PtfaKTZzg_rRp)

**Comment by awhicks** [comment]
I didn't initially add the whole folder because the folder could use a bit of cleaning before it got posted but then I forgot to mention that, the formatting for Ayaan's CV is all messed up and the v1 folder is I think either all blank or has an older copy of one of the included files so might just confuse people
